# MANUALLY ADD PUBLICATIONS THROUGH THIS FILE
- id: doi:10.1089/omi.2024.0004
  image: images/papers/rodrigues2024.jpg
- id: doi:10.1016/J.NEUROSCIENCE.2024.09.012
  image: images/papers/desouza2024.jpg
- id: doi:10.1002/cam4.6481
  image: images/papers/ferraz2023.jpg
- id: doi:10.3389/fgene.2022.814437
  image: images/papers/morais2022.jpg
- id: doi:10.1109/CIBCB58642.2024.10702116
  image: images/papers/cavalcante2024.png
- id: doi:10.1093/molbev/msaa252
  image: images/lines/evo2.jpeg
- id: doi:10.1007/s10142-021-00794-9
  image: images/lines/evo3.jpg
- id: doi:10.1038/s41598-019-52299-y
  image: images/lines/evo4.jpg
- id: doi:10.3390/cancers13081860
  image: images/lines/networks.png
- id: doi:10.1101/2022.10.18.512769
  image: images/lines/metagenomics_2.jpg
- id: doi:10.3390/microorganisms11071668
  image: images/lines/metagenomics_2.jpg
- id: doi:10.3389/fgene.2019.00791
  image: images/lines/transcriptomics_1.jpg
- id: doi:10.1093/bioinformatics/btz007
  image: images/tools/transcriptogramer.png
- id: doi:10.1007/s12031-024-02203-9
  image: images/papers/michaelsen2024.jpg
- id: doi:10.1093/molbev/msae019
  image: images/papers/campos2024.jpeg
- id: doi:10.1080/10408444.2018.1429387
  image: images/papers/desouza2018.jpg
- id: doi:10.1089/jmf.2017.0130
  image: images/papers/camara2018.jpg
- id: doi:10.3390/biomedicines9101297
  image: images/papers/oliveira2021.png
- id: doi:10.1093/bioinformatics/btab819
  image: images/papers/cardoso2022.jpeg
- id: doi:10.1093/nar/gkn636
  image: images/lines/evo5.jpeg
- id: doi:10.1371/journal.pone.0082457
  image: images/papers/albanus2013.png
- id: doi:10.1016/j.jhazmat.2024.136866
